-- Create Admin Users Table
CREATE TABLE IF NOT EXISTS villingili_admin_users (
    id bigint generated by default as identity primary key,
    telegram_id bigint unique not null,
    username text,
    phone_number text,
    password text not null, -- Storing plain text to allow showing it to admin
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table villingili_admin_users enable row level security;

-- Policy: Only Service Role can manage this table (since we use API)
create policy "Service Role Full Access"
on villingili_admin_users
for all
to service_role
using ( true )
with check ( true );
